### PR TITLE
Add JSONSerializationTests for JSONValue bug

### PR DESCRIPTION
**Pull request by lawmicha**
*Issue #, if available:*
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/401

*Description of changes:*
This adds a unit test related to issue detailed in https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/401 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by LachlanMcCulloch — APPROVED** [review]

**Review by palpatim — COMMENTED** [review]
This test appears to validate the approach, which I'm fine with, but doesn't actually exercise the code added into the SubscriptionWatcher by https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/402, right? Would it be possible to add a test to confirm that behavior, or can you confirm that existing tests exercise the new code?

**Comment by lawmicha** [comment]
> This test appears to validate the approach, which I'm fine with, but doesn't actually exercise the code added into the SubscriptionWatcher by [awslabs#402](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/402), right? Would it be possible to add a test to confirm that behavior, or can you confirm that existing tests exercise the new code?

Good question, there are existing integration tests in [SubscriptionTests](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/c4a062c7d68cc8a09e561e8388c89913829fdbfd/AWSAppSyncIntegrationTests/SubscriptionTests.swift) that cover the code in the PR and since it's an intergration level test, actually makes it to the [serialization](https://github.com/aws-amplify/aws-appsync-realtime-client-ios/blob/main/AppSyncRealTimeClient/Connection/AppSyncConnection/AppSyncSubscriptionConnection+Connection.swift#L49) done by AppSyncRealTimeClient.

**Comment by LachlanMcCulloch** [comment]
@palpatim @lawmicha Can I merge these changes into the existing PR?

**Comment by lawmicha** [comment]
> @palpatim @lawmicha Can I merge these changes into the existing PR?

yes, please go ahead, then we'll merge your [PR](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/402) in once this is applied on top of that branch

**Pull request merged**
